### ISSUE TITLE
D3D11 crash

### ISSUE THREAD

**Issue by Zero-One101** [AxioDL/boo#12]
Launch URDE with the --d3d11 flag and load up a HECL project. Wait long enough and it will crash with the following error:

"FATAL ERROR [boo::D3D11] The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action"

GPU: nVidia GTX 980Ti

**Comment by jackoalan** [comment]
Determined cause to be rectangle out of viewport bounds
