### ISSUE TITLE
Problem building boo on Win 10

### ISSUE THREAD

**Issue by LASTWINDOW** [AxioDL/boo#14]
I was trying to build URDE following the building instructions from the readme but the building of boo kept failing. The compiler said that it didn't know what "DEVICE_SCALE_FACTOR_INVALID" from line 1101 of WindowWin32.cpp was, so following [this](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/um/ShTypes.Idl) I replaced it with a 0 and it let me compile the whole thing.

CMake 3.8.0-rc1
Python 3.6.0
Visual Studio 2015
Windows 10 Pro

**Comment by jackoalan** [comment]
Thanks for the report,

I find it odd that the DEVICE_SCALE_FACTOR enum itself is available, but not the DEVICE_SCALE_FACTOR_INVALID value. In any case, I'll change it to 0 to account for whatever header difference you have on your system.

**Comment by Antidote** [comment]
It's probably an Update version difference, Microsoft _loves_ to break things arbitrarily.

**Comment by jackoalan** [comment]
Yea, I think I'm still running VS2015 Update 2, I should probably update it to 3 or whatever's current
