### ISSUE TITLE
fix build

### ISSUE THREAD

**Issue by derselbst** [AxioDL/boo#15]
gcc compiles `pffft.c` in pedantic mode, thus `M_PI` and `M_SQRT2` are undeclared. To fix that, pls add `#undef __STRICT_ANSI__` before including math.h or get rid of pedantic mode.

**Comment by Antidote** [comment]
I see no reason to use pedantic mode, so unless jack has a reason i think that's the route we should take

**Comment by jackoalan** [comment]
I just pushed a commit without -pedantic. Let me know if it builds correctly for you.

**Comment by derselbst** [comment]
I was mistaken, the `-pedantic` flag didnt caused it. Problem is that when building boo from amuse something in between (couldnt find it) adds a `-std=c99` flag. However to make the math defines work we need `-std=gnu99`. Adding `set(CMAKE_C_STANDARD 99)` to boo's CMakeLists should do the trick (dunno about setting `CMAKE_C_STANDARD_REQUIRED` though).
